# Makefile automatically generated by bomrelease version 1.12
#
# scc version 4.03 (2008-06-07)

PROGRAM = scc
SOURCE  = stderr.c filter.c scc.c
OBJECT  = stderr.o filter.o scc.o
DEBRIS  = a.out core *~
OFLAGS  = -g
WFLAGS  = # -Wall -Wmissing-prototypes -Wstrict-prototypes -std=c89 -pedantic
UFLAGS  = # Set on command line only
IFLAGS  = # -I directory options
DFLAGS  = # -D define options
CFLAGS  = ${OFLAGS} ${UFLAGS} ${WFLAGS} ${IFLAGS} ${DFLAGS}


all: ${PROGRAM}

${PROGRAM}: ${OBJECT}
	${CC} -o $@ ${CFLAGS} ${OBJECT} ${LDFLAGS} ${LDLIBES}

clean:
	rm -f ${OBJECT} ${DEBRIS}

realclean: clean
	rm -f ${PROGRAM}

depend: ${SOURCE}
	mkdep -fscc.mk ${SOURCE}

# DO NOT DELETE THIS LINE or the blank line after it -- make depend uses them.

filter.o: filter.c
filter.o: filter.h
filter.o: stderr.h
scc.o: filter.h
scc.o: scc.c
scc.o: stderr.h
stderr.o: stderr.c
stderr.o: stderr.h
